Updated to pull from environment rather than hardcoded entries

diff --git a/cookbooks/bamboo-server/templates/default/rpm-package.erb b/cookbooks/bamboo-server/templates/default/rpm-package.erb
--- a/cookbooks/bamboo-server/templates/default/rpm-package.erb
+++ b/cookbooks/bamboo-server/templates/default/rpm-package.erb
@@ -129,7 +129,7 @@ rpm_working_dir="$working_dir/build/rpmbuild"
 create_control(){
 cd $working_dir
 # Grabs the spec file and startup script from GIT
-git clone --quiet git@github:deployment.git; if [ "$?" -gt "0" ]; then echo "Error occurred with GIT repository."; clean; exit 1; fi
+git clone --quiet git@<%=node[:git_repo] %>:deployment.git; if [ "$?" -gt "0" ]; then echo "Error occurred with GIT repository."; clean; exit 1; fi
 # This will parse the spec file and replace branch and build with the correct numbers
 if [ -f deployment/$application_name.spec ]; then
 	cat deployment/$application_name.spec | sed -e s/{branch}/$branch/g | sed -e s/{build}/$build/g > $application_name.spec.tmp; mv $application_name.spec.tmp $rpm_working_dir/SPECS/$application_name.spec
@@ -181,10 +181,10 @@ rpmbuild -bb --clean --rmsource --quiet SPECS/$application_name.spec; if [ "$?" 
 
 # After the RPM is built, move it over to the yum repo
 echo "Moving the RPM to the yum repository."
-rsync -q -e ssh -av /opt/atlassian/bamboo/rpmbuild/RPMS/noarch/$application_package ubuntu@github:/storage/yum-repo/testing/$application_package; if [ "$?" -gt "0" ]; then echo "Error occurred pushing to yum repo."; clean; exit 1; fi
+rsync -q -e ssh -av /opt/atlassian/bamboo/rpmbuild/RPMS/noarch/$application_package <%= node[:yum_user] %>@<%= node[:yum-repo_host] %>:<%= node[:yum_dir] %>/testing/$application_package; if [ "$?" -gt "0" ]; then echo "Error occurred pushing to yum repo."; clean; exit 1; fi
 
 # Now run the updaterepo process to update yum repository information
-$ssh_command ubuntu@github "sudo yum-update > /dev/null 2>&1"; sleep 60
+$ssh_command <%= node[:yum_user] %>@<%= node[:yum-repo_host] %> "sudo yum-update > /dev/null 2>&1"; sleep 60
 
 # Clean up the files used by RPM during packaging, just to be clean
 echo "Cleaning up our working directories."
@@ -242,7 +242,7 @@ promote(){
 # This will promote a build from the QA (Testing) repository to the Certified Software (Release) repository.
 app_target="$application_name"
 app_version="$version"
-$ssh_command ubuntu@github "rsync -av /storage/yum-repo/testing/$application_target-$version.noarch.rpm /storage/yum-repo/release/$application_target-$version.noarch.rpm; sudo yum-update"
+$ssh_command <%= node[:yum_user] %>@<%= node[:yum-repo_host] %> "rsync -av <%= node[:yum_dir] %>/testing/$application_target-$version.noarch.rpm <%= node[:yum_dir] %>/release/$application_target-$version.noarch.rpm; sudo yum-update"
 echo "Version has been promoted."
 }
 
