Updated to fix the chef-provision to use a function for error checking.

diff --git a/cookbooks/altisource/templates/default/chef-provision.erb b/cookbooks/altisource/templates/default/chef-provision.erb
--- a/cookbooks/altisource/templates/default/chef-provision.erb
+++ b/cookbooks/altisource/templates/default/chef-provision.erb
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+check_errs()
+{
+  # Function. Parameter 1 is the return code
+  # Para. 2 is text to display on failure.
+  if [ "${1}" -ne "0" ]; then
+    echo "ERROR # ${1} : ${2}"
+    # as a bonus, make our script exit with the right error code.
+    exit ${1}
+  fi
+}
+
 enter_host(){
 echo "Enter the fully qualified hostname of the system to provision."
 read answer
@@ -59,35 +70,25 @@ if [ "$hostcheck" != "" ]; then
 fi
 # Hostname was passed and nslookup succeeded, proceed with provisioning.
 knife bootstrap $host --distro rhel6-gems && echo "Chef has been provisioned to the host." 
-if [ $? -gt 0 ]; then
- echo "There was a problem with the bootstrap."; exit 1
-fi
+check_errs $? "There was a problem with the bootstrap."
 
 # Add node to the new environment.
 knife node set_environment $host $env_targ
-if [ $? -gt 0 ]; then
- echo "There was a problem with adding the node to the environment."; exit 1
-fi
+check_errs $? "There was a problem with adding the node to the environment."
 
 # Add role all automatically to the new node.
 knife node run_list add $host role[all] && echo "Role all has been added to the node." 
-if [ $? -gt 0 ]; then
- echo "There was a problem with adding the all role."; exit 1
-fi
+check_errs $? "There was a problem with adding the all role."
 
 # Add any other roles that were selected.
 for i in `echo $add_role`; do
   knife node run_list add $host "$i" && echo "Role $i has been added to the node." 
-  if [ $? -gt 0 ]; then
-    echo "There was a problem with adding $i role."; exit 1
-  fi
+  check_errs $? "There was a problem with adding $i role."
 done
 
 # SSH to the new node and run chef-client.
 ssh root@$host "chef-client" && echo "Initial chef-client run has been completed." 
-if [ $? -gt 0 ]; then
-  echo "There was a problem with the chef client run, check the logs."; exit 1
-fi
+check_errs $? "There was a problem with the chef client run, check the logs."
 }
 
 chef_check(){
